### ISSUE TITLE
GPT4 API is slower than previous version of the software

### ISSUE THREAD

**Issue by MrFutureV** [gnehs/subtitle-translator-electron#92]
i have no idea why,its been happening since the new version of subtitle-translator-electron released,it just way slower than the old version and there will also be bugs in the production of subtitles.
![20231110110638](https://github.com/gnehs/subtitle-translator-electron/assets/46783891/ca2df5f0-1cfe-4ce5-9680-194ced5b68eb)
repetitive productions as well
![QQ截图20231110123346](https://github.com/gnehs/subtitle-translator-electron/assets/46783891/12a4fd5d-9e28-4e9f-836d-29897f124f4e)

**Comment by gnehs** [comment]
In the new version, a delay function has been added to avoid OpenAI rejecting requests due to excessive requests. You can reduce this value to improve speed.

<img width="801" alt="image" src="https://github.com/gnehs/subtitle-translator-electron/assets/16719720/993ee0c2-25cf-4739-86d2-71ba876cea7b">
